name: CI - Syntax & Smoke Test

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bcrypt python-dotenv mysql-connector-python || true
      - name: Syntax compile check
        run: python -m py_compile main.py

  # Optional: add a job later for integration with a real MySQL server
